### ISSUE TITLE
Exporting class results in interface instead of class 

### ISSUE THREAD

**Issue by SantoJambit** [FlorianRappl/dets#1]
# Bug Report

Moved from Piral:

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral 0.10.9

## Description

When trying to export a class, you get an interface

## Steps to Reproduce

1. export a class

## Expected behavior

a class export declaration

## Actual behavior

an interface export declaration

## Possible Origin / Solution

See the MWE: https://github.com/SantoJambit/shell-mwe/commit/f4def2358c36b45e052b6aec1de3ec8f772587ed

**Comment by FlorianRappl** [comment]
A failing (isolated) test would be appreciated. Thanks!

Keep in mind that it should export a `const` / `class` whatever instance as this is the nature of `default`. The type of this instance is the interesting part. If its `any` but should not be then indeed this is an issue, otherwise it works as it should.

**Comment by SantoJambit** [comment]
It seems you already created an isolated test. I'm assuming your comment was about the other issue.

**Comment by FlorianRappl** [comment]
Yes, this is currently still open. Need to find how constructors can be reliably resolved.
